apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: spring-boot-hello
  template:
    metadata:
      labels:
        app: spring-boot-hello
    spec:
      containers:
        - name: spring-cloud-discovery
          images:
          default:
            image: naresh240/spring-boot-hello
            tag: ${imageTag}
